name: zizmor

on:
  workflow_call:

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check out caller repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Check out shared configuration
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: obbywiki/shared-workflows
          ref: main
          path: .shared-workflows
          persist-credentials: false
          sparse-checkout: |
            .github/zizmor.yml
          sparse-checkout-cone-mode: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482
        with:
          inputs: .github/workflows
          config: .shared-workflows/.github/zizmor.yml
          advanced-security: ${{ !github.event.repository.private }}
